version: '3.1'

services:
  database:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 5432:5432
      
volumes:
  db-data: