POST http://localhost:3000
Content-Type: application/json

{
  "name": "John Doe",
  "email": "XD"
}

###
POST http://localhost:3000/initPlayer
Content-Type: application/json

{
  "discordId": "HEHE",
  "discordDisplayName": "Jon Poe"
}
###
POST http://localhost:3000/checkBalance
Content-Type: application/json

{
  "discordId": "12e3456"
}
###
POST http://localhost:3000/buyItem
Content-Type: application/json

{
  "discordId": "456",
  "itemName": "1"
}
###
POST http://localhost:3000/updatePlayer
Content-Type: application/json

{
  "discordId": "123456"
}
###

POST http://localhost:3000/getShopForPlayer
Content-Type: application/json

{
  "discordId": "184366854674972672"
}

###
GET http://localhost:3000/allPlayers
###
POST http://localhost:3000/addBitToPlayer
Content-Type: application/json
Authorization: Bearer PwdkIEkslESQweFso1Odw3DxC22Ax4

{
  "discordId": "123"
}
###
POST http://localhost:3000/blacklistPlayer
Content-Type: application/json

{
  "discordId": "184366854674972672"
}
###
POST http://localhost:3000/unblacklistPlayer
Content-Type: application/json

{
  "discordId": "184366854674972672"
}

###

POST http://localhost:3000/redeemDaily
Content-Type: application/json

{
  "discordId": "184366854674972672"
}